### ISSUE TITLE
WorkComputer alternative solutions

### ISSUE THREAD

**Issue by madushan1000** [AidanFray/CTF_Writeups#1]
I found some more ways to complete this challange. We can use `tar` to just add the file into an archive and print the content on screen. 
```
$tar cvf - README.flag
README.flag                                                                                         0000400 0002472 0002472 00000000034 13504125515 010414  0
ustar   1338                            1338
README.flag
CTF{4ll_D474_5h4ll_B3_Fr33}
```

also for the bonus flag, we have access to `upx`, which is used to pack binaries. So we can just do this.
```
$upx  -ochmod /bin/busybox
```
which will repack busybox and output to `./chmod`, it'll also set executable bits properly. Then we can
```
$./chmod +r ORME.flag
$tar cvf - ORME.flag
ORME.flag                                                                                           0000444 0002472 0002472 00000000041 13504123723 010226  0
ustar   1338                            1338
ORME.flag
CTF{Th3r3_1s_4lw4y5_4N07h3r_W4y}
```

**Comment by bx-r0** [comment]
Brilliant, thank you for this. 

I added a "Alternative Solutions" section to the README with credit to these solutions in c93e4c297ad52f5aedc2e404777612a80a23db9a.
